### ISSUE TITLE
Human Parser Graphonomy 

### ISSUE THREAD

**Issue by vinodbukya6** [xiezhy6/PASTA-GAN-plusplus#8]
Hi @xiezhy6,
Hope you are well. Thank you so much for your work. I have tested inference on Colab and working completely fine. When I test with custom images facing issues as I am not able to generate Garment Segmentation image. How can I generate segmentation image?

From test data sample images:
Image: 
![16_8533AAA1AE4F33GS_2524699_urban-revivo-6435-9964252-4](https://user-images.githubusercontent.com/46157647/199874960-2f079cf6-20f2-402e-a09b-35a10e4f4017.jpg)
Garment Segmentation(No human body parts): 
![16_8533AAA1AE4F33GS_2524699_urban-revivo-6435-9964252-4](https://user-images.githubusercontent.com/46157647/199874764-a54b4755-d620-443c-967b-35de7327de1c.png)
Human Parser:
![16_8533AAA1AE4F33GS_2524699_urban-revivo-6435-9964252-4](https://user-images.githubusercontent.com/46157647/199874886-bb23f3d3-8904-4345-ae78-bedcfc66912b.png)

Garment Segmentation and Human Parser images are different.

**Comment by ush-gan** [comment]
Did you solve the Garment Segmentation?

**Comment by vinodbukya6** [comment]
Hi @ush-gan
Not solved the Segmentation issue.

**Comment by vinodbukya6** [comment]
Hi @xiezhy6 
Is there any update on Garment Segmentation pre-processing method?

**Comment by vinodbukya6** [comment]
Hi @ush-gan 
Issue solved after following below steps.
Generated Human Parser Image from here: https://github.com/Gaoyiminggithub/Graphonomy using Graphonomy(PASCAL) Model. 
Put generated Parser Image in parsing & garment_parsing directories.
Generate Openpose Key-points.
and Test the model after test set is prepared.

Thank you!
